"""Initial schema

Revision ID: 6cb3d67c3307
Revises: 
Create Date: 2026-04-12 18:34:55.763437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cb3d67c3307'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS users;")
    op.execute("CREATE SCHEMA IF NOT EXISTS drivers;")
    op.execute("CREATE SCHEMA IF NOT EXISTS rides;")
    op.execute("CREATE SCHEMA IF NOT EXISTS stands;")
    op.execute("CREATE SCHEMA IF NOT EXISTS pricing;")
    op.execute("CREATE SCHEMA IF NOT EXISTS payments;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_pricing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('base_fare', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('per_km_rate', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('per_minute_wait', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('initial_dead_flat', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('initial_dead_per_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('initial_dead_free_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('return_dead_per_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('return_dead_cap', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('return_surcharge', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('driver_share_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ap_commission_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('min_fare', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='pricing'
    )
    op.create_index(op.f('ix_pricing_zone_pricing_id'), 'zone_pricing', ['id'], unique=False, schema='pricing')
    op.create_table('stands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('total_capacity', sa.Integer(), nullable=True),
    sa.Column('opens_at', sa.TIME(), nullable=True),
    sa.Column('closes_at', sa.TIME(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='stands'
    )
    op.create_index(op.f('ix_stands_stands_id'), 'stands', ['id'], unique=False, schema='stands')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_index(op.f('ix_users_users_id'), 'users', ['id'], unique=False, schema='users')
    op.create_index(op.f('ix_users_users_phone_number'), 'users', ['phone_number'], unique=True, schema='users')
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=20), nullable=True),
    sa.Column('vehicle_make', sa.String(length=50), nullable=True),
    sa.Column('vehicle_model', sa.String(length=50), nullable=True),
    sa.Column('vehicle_photo_url', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=30), nullable=True),
    sa.Column('license_expiry', sa.DATE(), nullable=True),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('total_rides', sa.Integer(), nullable=True),
    sa.Column('acceptance_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cancellation_count', sa.Integer(), nullable=True),
    sa.Column('rejection_count', sa.Integer(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('current_stand_id', sa.Integer(), nullable=True),
    sa.Column('current_lat', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('current_lng', sa.DECIMAL(precision=9, scale=6), nullable=True),
    sa.Column('last_location_update', sa.TIMESTAMP(), nullable=True),
    sa.Column('upi_id', sa.String(length=100), nullable=True),
    sa.Column('bank_account_no', sa.String(length=30), nullable=True),
    sa.Column('bank_ifsc', sa.String(length=15), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('fcm_token', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['current_stand_id'], ['stands.stands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_registration'),
    schema='drivers'
    )
    op.create_index(op.f('ix_drivers_drivers_id'), 'drivers', ['id'], unique=False, schema='drivers')
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_code', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('stand_id', sa.Integer(), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('pickup_lng', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('drop_address', sa.Text(), nullable=False),
    sa.Column('drop_lat', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('drop_lng', sa.DECIMAL(precision=9, scale=6), nullable=False),
    sa.Column('initial_dead_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('active_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('return_dead_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_km', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('driver_arrived_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ride_started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('ride_completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('zone', sa.String(length=20), nullable=True),
    sa.Column('base_fare', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('per_km_rate', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('active_fare', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('initial_dead_charge', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('return_surcharge', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('waiting_charge', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_customer_fare', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('return_dead_compensation', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('driver_earning', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('ap_commission', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ride_otp', sa.String(length=4), nullable=True),
    sa.Column('customer_rating', sa.Integer(), nullable=True),
    sa.Column('driver_rating', sa.Integer(), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.drivers.id'], ),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.stands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rides'
    )
    op.create_index(op.f('ix_rides_rides_booking_code'), 'rides', ['booking_code'], unique=True, schema='rides')
    op.create_index(op.f('ix_rides_rides_id'), 'rides', ['id'], unique=False, schema='rides')
    op.create_table('stand_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stand_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.stands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stand_id', 'driver_id'),
    schema='stands'
    )
    op.create_index(op.f('ix_stands_stand_queue_id'), 'stand_queue', ['id'], unique=False, schema='stands')
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=100), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.drivers.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.rides.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='payments'
    )
    op.create_index(op.f('ix_payments_transactions_id'), 'transactions', ['id'], unique=False, schema='payments')
    op.create_table('ride_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('stand_id', sa.Integer(), nullable=True),
    sa.Column('offered_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('response', sa.String(length=20), nullable=True),
    sa.Column('responded_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('distance_to_pickup', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.drivers.id'], ),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.rides.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.stands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rides'
    )
    op.create_index(op.f('ix_rides_ride_offers_id'), 'ride_offers', ['id'], unique=False, schema='rides')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rides_ride_offers_id'), table_name='ride_offers', schema='rides')
    op.drop_table('ride_offers', schema='rides')
    op.drop_index(op.f('ix_payments_transactions_id'), table_name='transactions', schema='payments')
    op.drop_table('transactions', schema='payments')
    op.drop_index(op.f('ix_stands_stand_queue_id'), table_name='stand_queue', schema='stands')
    op.drop_table('stand_queue', schema='stands')
    op.drop_index(op.f('ix_rides_rides_id'), table_name='rides', schema='rides')
    op.drop_index(op.f('ix_rides_rides_booking_code'), table_name='rides', schema='rides')
    op.drop_table('rides', schema='rides')
    op.drop_index(op.f('ix_drivers_drivers_id'), table_name='drivers', schema='drivers')
    op.drop_table('drivers', schema='drivers')
    op.drop_index(op.f('ix_users_users_phone_number'), table_name='users', schema='users')
    op.drop_index(op.f('ix_users_users_id'), table_name='users', schema='users')
    op.drop_table('users', schema='users')
    op.drop_index(op.f('ix_stands_stands_id'), table_name='stands', schema='stands')
    op.drop_table('stands', schema='stands')
    op.drop_index(op.f('ix_pricing_zone_pricing_id'), table_name='zone_pricing', schema='pricing')
    op.drop_table('zone_pricing', schema='pricing')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS users CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS drivers CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS rides CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS stands CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS pricing CASCADE;")
    op.execute("DROP SCHEMA IF EXISTS payments CASCADE;")
